site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/backstage/backstage
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - What is Backstage?: 'overview/what-is-backstage.md'
      - Architecture overview: 'overview/architecture-overview.md'
      - Project Roadmap: 'overview/roadmap.md'
      - Vision: 'overview/vision.md'
      - The Spotify Story: 'overview/background.md'
      - Strategies for adopting: 'overview/adopting.md'
      - Release & Versioning Policy: 'overview/versioning-policy.md'
      - Backstage Threat Model: 'overview/threat-model.md'
      - Support and community: 'overview/support.md'
      - Logo assets: 'overview/logos.md'
  - Getting Started:
      - Creating your Backstage App: 'getting-started/index.md'
      - Configuring Backstage:
          - Database: 'getting-started/config/database.md'
          - Authentication: 'getting-started/config/authentication.md'
          - Configuring App with plugins: 'getting-started/configure-app-with-plugins.md'
          - Customize the look-and-feel of your App: 'getting-started/app-custom-theme.md'
          - Customizing your Homepage: 'getting-started/homepage.md'
      - Using Backstage:
          - Logging in: 'getting-started/logging-in.md'
          - Register a component: 'getting-started/register-a-component.md'
          - Create a component: 'getting-started/create-a-component.md'
      - Keeping Backstage Updated: 'getting-started/keeping-backstage-updated.md'
      - Key Concepts: 'getting-started/concepts.md'   