apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pets-api
  description: API that manages pets in the Spring PetClinic application.
  annotations:
    backstage.io/lifecycle: production
  tags:
    - pets
    - petclinic
    - healthcare
spec:
  type: openapi
  lifecycle: production
  owner: team-clinic
  definition: |
    openapi: 3.0.0
    info:
      title: Pets API
      description: API for managing pets in the Spring PetClinic application.
      version: 1.0.0
    paths:
      /owners/{ownerId}/pets:
        get:
          summary: Get all pets for an owner
          operationId: getPetsByOwner
          tags:
            - pets
          parameters:
            - name: ownerId
              in: path
              required: true
              description: The ID of the owner
              schema:
                type: integer
                format: int64
          responses:
            '200':
              description: A list of pets belonging to the owner
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
            '404':
              description: Owner not found
        post:
          summary: Add a new pet for an owner
          operationId: addPet
          tags:
            - pets
          parameters:
            - name: ownerId
              in: path
              required: true
              description: The ID of the owner
              schema:
                type: integer
                format: int64
          requestBody:
            description: Pet object that needs to be added
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Pet'
          responses:
            '201':
              description: Pet successfully added
            '400':
              description: Invalid request
      /owners/{ownerId}/pets/{petId}:
        get:
          summary: Get details of a pet
          operationId: getPetById
          tags:
            - pets
          parameters:
            - name: ownerId
              in: path
              required: true
              description: The ID of the owner
              schema:
                type: integer
                format: int64
            - name: petId
              in: path
              required: true
              description: The ID of the pet
              schema:
                type: integer
                format: int64
          responses:
            '200':
              description: Details of the pet
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Pet'
            '404':
              description: Pet not found
        put:
          summary: Update pet details
          operationId: updatePet
          tags:
            - pets
          parameters:
            - name: ownerId
              in: path
              required: true
              description: The ID of the owner
              schema:
                type: integer
                format: int64
            - name: petId
              in: path
              required: true
              description: The ID of the pet
              schema:
                type: integer
                format: int64
          requestBody:
            description: Updated pet object
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Pet'
          responses:
            '200':
              description: Pet successfully updated
            '400':
              description: Invalid request
    components:
      schemas:
        Pet:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            birthDate:
              type: string
              format: date
            type:
              type: string
              description: Type of the pet (e.g., Dog, Cat)
            visits:
              type: array
              items:
                $ref: '#/components/schemas/Visit'
        Visit:
          type: object
          properties:
            id:
              type: integer
              format: int64
            date:
              type: string
              format: date
            description:
              type: string
              description: Description of the visit
